FROM dhi.io/node:25-alpine3.23-sfw-ent-dev as base

ENV PNPM_HOME="/pnpm"
ENV PATH="${PNPM_HOME}"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

COPY . .

EXPOSE 5173

CMD [ "pnpm", "dev", "--host", "0.0.0.0" ]